name:  SpoutLogin
version:  0.0.4
description:  Spout Popup for Login
author:  rbs90
website:  http://tu-chemnitz.de/~rbs
depend: [Spout]

main:  de.rbs90.bukkit.plugins.spoutlogin.MainAuthentificate

commands:
    slogin:
          description: Login via Spout interface.
          usage: /<command>